"""Add interests field to User

Revision ID: 603dd82892e9
Revises: c5cc32115ad6
Create Date: 2025-06-03 12:22:26.352214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603dd82892e9'
down_revision = 'c5cc32115ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', sa.Text(), nullable=True))
        batch_op.drop_column('audio_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('interests')

    # ### end Alembic commands ###
